Removed reveal line for insert copy action
cursorless-dev/cursorless pull request #1579
Opened 2023-07-05 11:06 UTC by AndreasArvidsson

Fixes #1437

## Checklist

- [ ] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [ ] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [ ] I have not broken the cheatsheet

2023-07-09 14:17 UTC, pokey reviewed
I'm a bit confused how this one would address all the issues in #1437, when this change appears to only impact "clone" and "clone up"

2023-07-09 14:20 UTC, AndreasArvidsson commented
> I'm a bit confused how this one would address all the issues in #1437, when this change appears to only impact "clone" and "clone up"

The behavior of clone and bring is now consistent. ie we do not scroll on either. The behavior of ctrl-z I don't think we can really influence that much.

2023-07-13 11:01 UTC, pokey approved these changes

2023-07-13 11:11 UTC, pokey requested changes
whoops; broken in case where new target contains cursor; that should reveal selection

2023-07-13 11:14 UTC, pokey commented on packages/cursorless-engine/src/actions/InsertCopy.ts
> +    ) {
```suggestion
    ) {
        // If the original target contained the user's cursor, reveal it in case it got pushed off screen
```

2023-07-13 11:14 UTC, pokey commented on packages/cursorless-engine/src/actions/InsertCopy.ts
> +        // If the original target contained the user's cursor, reveal it in case it got pushed off screen
```suggestion
      // If the original target contained the user's cursor, reveal it in case it got pushed off screen
```

2023-07-13 11:14 UTC, pokey approved these changes

2023-07-13 11:55 UTC, merged