Clarify extension dependency instructions for adding a new language
cursorless-dev/cursorless pull request #1903
Opened 2023-09-18 01:54 UTC by fidgetingbits

Following a discussion on Slack between Andreas and River about the Elixir PR tests failing, it seems like the docs needed to be updated to clarify how to add an extension dependency when adding support for a language type that vscode isn't natively aware of.

## Checklist

- [ ] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [x] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [ ] I have not broken the cheatsheet

2023-09-18 02:11 UTC, r-tae reviewed
LGTM apart from that typo

2023-09-18 02:11 UTC, r-tae commented on docs/contributing/adding-a-new-language.md
> +If you are adding support for a new language that isn't natively detected by VSCode, you will need to add the appropriate extension to the list of dependencies. The list of languages officially suppo
Talon typo
```suggestion
If you are adding support for a new language that isn't natively detected by VSCode, you will need to add the appropriate extension to the list of dependencies. The list of languages officially supported by VSCode is listed [here](https://code.visualstudio.com/docs/languages/identifiers). You can add the extension to `packages/common/src/extensionDependencies.ts` and then re-run `pnpm init-vscode-sandbox` to ensure it is installed. If you do not do this you will encounter errors when attempting to execute cursorless commands in the next step. See [here](https://github.com/cursorless-dev/cursorless/issues/1895)
```

2023-09-27 14:05 UTC, pokey approved these changes
Made some minor tweaks but otherwise looks good

2023-09-27 14:05 UTC, pokey commented on docs/contributing/adding-a-new-language.md
> +If you are adding support for a new language that isn't natively detected by VSCode, you will need to add the appropriate extension to the list of dependencies. The list of languages officially suppo
```suggestion
If you are adding support for a new language that isn't natively detected by VSCode, you will need to add the appropriate extension to the list of dependencies. The list of languages officially supported by VSCode is listed [here](https://code.visualstudio.com/docs/languages/identifiers). If your language is in that list, you can skip this step and proceed to step 3. If your language is not in that list, you need to find a VSCode extension that adds support for your language, and add the id of the given extension to [`packages/common/src/extensionDependencies.ts`](../../packages/common/src/extensionDependencies.ts) and then re-run `pnpm init-vscode-sandbox` to ensure it is installed. If you do not do this you will encounter errors when attempting to execute cursorless commands in the next step. See [here](https://github.com/cursorless-dev/cursorless/issues/1895)
```

2023-09-28 12:24 UTC, AndreasArvidsson approved these changes

2023-09-28 12:25 UTC, pokey requested changes
things were kinda messed up in the deploy preview; I think I fixed it but waiting to double check

2023-09-28 12:26 UTC, AndreasArvidsson approved these changes

2023-09-28 14:22 UTC, pokey approved these changes
Ok looking good now!

2023-09-28 14:42 UTC, merged