Make parameter `cursorlessSnippetsDir` optional
cursorless-dev/cursorless pull request #2506
Opened 2024-07-13 19:12 UTC by AndreasArvidsson

## Checklist

- [/] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [/] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [/] I have not broken the cheatsheet

2024-07-15 15:52 UTC, pokey approved these changes

2024-07-15 15:53 UTC, pokey requested changes
See above

2024-07-15 16:01 UTC, AndreasArvidsson commented
I'm not against that, but I wonder if we gonna need that parameter once we moved to the new community snippets?

2024-07-16 14:24 UTC, pokey approved these changes
fair

2024-07-16 14:36 UTC, merged