Downgrade vscode engine
cursorless-dev/cursorless pull request #497
Opened 2022-01-19 21:45 UTC by bra1nDump

I work at Meta (previously Facebook) and we have an internal build of vscode. Usually we're running a little behind. Our current version is 1.58.x. Pretty much all of our development is based in vscode, and I'm assuming more people than just me we'll end up using the software. 
![image](https://user-images.githubusercontent.com/12608159/150217608-8943c401-15cc-4dc7-b15f-70ae275601cd.png)

In this pull request
* Downgraded vscode engine, @types and vscode version downloaded for testing.
* Compiled the project and ran tests. All succeeded, 55 shown as pending. Not sure what pending means.

2022-01-20 07:17 UTC, pokey requested changes
Looks mostly ok but see comments

2022-01-20 07:17 UTC, pokey commented on src/test/runTest.ts
> +    const vscodeExecutablePath = await downloadAndUnzipVSCode('1.58.1');
This one is a showstopper for me. Please run the tests using the latest VSCode

2022-05-30 12:34 UTC, pokey reviewed
just realised i had a couple pending comments on this one.  shall we close it, or did you still need this?

2022-05-30 12:57 UTC, auscompgeek commented on package.json
> +		"ui", "workspace"
I presume this is required so that cursorless runs on the client rather than the remote. I don't think Talon would work well over SSH for example 😅

2022-05-30 13:41 UTC, pokey commented on package.json
> +		"ui", "workspace"
No Talon doesn't directly talk to cursorless.  Talon talks to the command server, which sends commands to cursorless.  Cursorless + Talon actually works fine over ssh

Fwiw, tho, I actually think we could add `"workspace", "ui"`, as Cursorless _should_ be able to run either client or server side

2022-05-31 02:52 UTC, auscompgeek commented on package.json
> +		"ui", "workspace"
Ah right. Probably a good idea anyway, the latency might get annoying.

2022-05-31 02:55 UTC, bra1nDump commented on package.json
> +		"ui", "workspace"
Yes I can't easily install a non-company approved extension on our server vscode. But it works perfectly fine when installed on the local machine. I think I can try changing the order to [workspace, ui]. That should work just as well

2022-05-31 02:58 UTC, bra1nDump commented
I still need this, I just haven't upgraded my work cursorless stuff for the past 4 months. 

I plan to refresh all my setup in the following week and will try to prep the pull requests so it can be solved long term (so I and any other ppl with restrictions on the server extensions don't have to make a custom build)

2022-05-31 11:26 UTC, pokey commented on package.json
> +		"ui", "workspace"
Fwiw I believe others have requested that as well

2022-06-22 14:17 UTC, pokey commented
Ok some of these changes are now merged into `main` as part of #768.  As of that PR, we now test Cursorless against legacy VSCode, but not as far back as 1.58.1.  If you'd like to test that far back, you'll need to figure out how to fix CI; can possibly do it just by checking version in tests and ignoring failures for the ones that are failing if we're on legacy VSCode, as the test failures are fairly minor I believe

2022-06-26 06:04 UTC, bra1nDump commented
Actually a just realized I can install the insider's edition, which is a much fresher built - 1.63 !! Closing this pull request

2022-06-26 06:04 UTC, closed without merging