Group and arrange settings
cursorless-dev/cursorless pull request #813
Opened 2022-07-02 19:09 UTC by paul-schaaf

closes #389 

I've taken the liberty to also group the hat settings. let me know if I should revert it!

For some reason one of the hat settings still shows up first. I've looked into the vscode docs but wasn't able to find anything on it.I am guessing it is a bug in vscode. But maybe I also made a mistake somewhere.

2022-07-03 01:40 UTC, auscompgeek requested changes

2022-07-03 01:40 UTC, auscompgeek commented on README.md
> +- `cursorless.hatSettings.maximumHatStylePenalty`: The maximum allowed penalty for a hat style. Any hat style whose penalty is greater than this amount will not be used. A hat style penalty is define
If these names change then we need some migration code for those that have modified these settings. I don't see any.

2022-07-04 09:59 UTC, pokey requested changes
Thanks for taking a crack at this one!  Good direction, but as @auscompgeek mentions, this PR will break everyone's Cursorless who has used any hat settings 😅.  You'll need to modify the code that reads the settings to be able to handle the old as well as the new paths

2022-07-04 09:59 UTC, pokey commented on package.json
> +				"cursorless.hatSettings.hatPenalties.maximumHatStylePenalty": {
This doesn't really have any impact on hat penalties, so I don't think I'd put it in that group
```suggestion
				"cursorless.hatSettings.maximumHatStylePenalty": {
```

2022-07-04 10:04 UTC, pokey commented on src/core/Decorations.ts
>        .get<IndividualHatAdjustmentMap>("individualHatAdjustments")!;
You can prob add a new function like the following:

```typescript
function getHatSetting<T>(name: string): T {
return vscode.workspace
      .getConfiguration("cursorless.hatSettings")
      .get<T>(name) ??
vscode.workspace
      .getConfiguration("cursorless")
      .get<T>(name);
}
```

2022-07-04 10:15 UTC, pokey requested changes
On second, thought, though, I'm not sure we want to group the hat settings.  The hat enablement settings are far more common than the other ones.  I think probably to arrange settings by how likely they are to be used, rather than category.  Here's the order I'd suggest:


1. Cursorless: Hat Size Adjustment
2. Cursorless: Hat Vertical Offset
3. Cursorless › Hat Enablement: Colors
4. Cursorless › Hat Enablement: Shapes
5. Cursorless › Colors: Light
6. Cursorless › Colors: Dark

Then after that I think they're all less common so doesn't matter as much

2022-07-04 12:41 UTC, paul-schaaf commented
@pokey done!

2022-07-04 12:48 UTC, pokey approved these changes
Great thanks!

2022-07-04 13:02 UTC, merged